<?php

namespace AppBundle\Repository;

/**
 * Nivel_certificadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Nivel_certificadoRepository extends \Doctrine\ORM\EntityRepository
{
}
