<?php

namespace AppBundle\Repository;

/**
 * RollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RollRepository extends \Doctrine\ORM\EntityRepository
{
}
